services:
    dynamic_form.factory:
        class: Linio\DynamicFormBundle\Form\FormFactory
        calls:
            - [setFormFactory, [@form.factory]]
            - [setConfiguration, [%dynamic_form.configuration%]]
            - [setFormlyMapper, [@formly.mapper]]

    formly.mapper:
    	class: Linio\DynamicFormBundle\FormlyMapper\FormlyMapper
    	calls:
    		- [setCsrfTokenManager, [@security.csrf.token_manager]]
