services:
    dynamic_form.factory:
        class: Linio\DynamicFormBundle\Form\FormFactory
        calls:
            - [setFormFactory, [@form.factory]]
            - [setConfiguration, [%dynamic_form.configuration%]]

    dynamic_form.formly_mapper:
        class: Linio\DynamicFormBundle\FormlyMapper\FormlyMapper
        calls:
            - [setCsrfTokenManager, [@security.csrf.token_manager]]
            - [setFormFactory, [@dynamic_form.factory]]
            - [setFormlyFieldFactory, [@container.formly_field]]

    container.formly_field:
        class: Linio\DynamicFormBundle\FormlyMapper\FormlyField\FormlyFieldFactory

    formly_field.choice:
        class: Linio\DynamicFormBundle\FormlyMapper\FormlyField\ChoiceField
        lazy: true
        tags:
            - {name: formly_field, alias: choice}

    formly_field.date:
        class: Linio\DynamicFormBundle\FormlyMapper\FormlyField\DateField
        lazy: true
        tags:
            - {name: formly_field, alias: date}

    formly_field.number:
        class: Linio\DynamicFormBundle\FormlyMapper\FormlyField\NumberField
        lazy: true
        tags:
            - {name: formly_field, alias: number}

    formly_field.text:
        class: Linio\DynamicFormBundle\FormlyMapper\FormlyField\TextField
        lazy: true
        tags:
            - {name: formly_field, alias: text}
