name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.1
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: PHP Lint
      run: composer lint:check
      
    - name: PHPUnit Tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Generate code coverage image
      run: php generate-code-coverage-image.php

    - name: Commit Code Coverage Image to Repo
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Carlos San Juan
        author_email: carlossanjuanc@gmail.com
        message: "Committing code coverage image"
        add: "docs/code-coverage.png"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
