name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: PHP Lint
      run: composer lint:check
      
    - name: PHPUnit Tests
      run: vendor/bin/phpunit --coverage-clover coverage.xml

    - name: Generate code coverage badge
      run: vendor/bin/php-coverage-badger coverage.xml .github/badges/coverage.svg

    - name: Commit code coverage badge
      uses: EndBug/add-and-commit@v5
      with:
        message: "[ci skip] feat: commit backend coverage badge"
        add: ".github/badges/coverage.svg"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
